kGeneralChannelName="general"
kAnnouncementsChannelName="announcements"
kControlsChannelName="controls"
kTraitorsInstructionsChannelName="traitors-instructions"
kTraitorsChatChannelName="traitors-chat"
kBanishedRoleName="banished"